---

- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Copy k3s binary to all node
  copy:                                                           
      src: /usr/local/bin/k3s
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
