---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Enable Firewalld port 6443
  firewalld:
    zone: work
    port: 6443/tcp
    permanent: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Enable Firewalld port 8472
  firewalld:
    zone: work
    port: 8472/tcp
    permanent: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Enable Firewalld port
  firewalld:
    zone: internal
    interface: cni0
    permanent: yes
    state: enabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
